### ISSUE TITLE
Is there a way to launch jobs within specific nodes? Or even to launch single core job on each node within a multi-node allocation? 

### ISSUE THREAD

**Issue by satishskamath** [vecma-project/QCG-PilotJob#165]
To give an example: Lets say I have 2 nodes (node1 and node2) allocated with 128 cores each. At the end I want a job such that it runs on 1 core within node1 and 1 core within node2 specifically. Is this even possible within QCG-pilot?

**Comment by LourensVeen** [comment]
Hi Satish,

There is currently no way to tell QCG-PilotJob to start a job on a specific node or core. If you can explain a bit more about why you want to do this, maybe we can find another way of solving it, or get a clear set of requirements worked out for a new feature?

There's some related discussion in https://github.com/psnc-qcg/QCG-PilotJob/issues/65. I solved it by skipping the QCG-PJ front-end and using the back-end directly, but this is a bit of a special case in that I use QCG-PJ as a library, and I don't need the workflow engine at all. So that may not work for you.

**Comment by pkopta** [comment]
Hi Satish,
As Lourens mentioned this is currently not possible. Some workaround is to specify a task with resource requirements `numCores=128`, `numNodes=1` with the `model=default` - the QCG-PilotJob should allocate entire node for your task, but run a single process. The downside is that no other task can use this node until the first one finishes.

**Comment by LourensVeen** [comment]
Actually, reading the question again, could it be that you want to run an MPI job across two nodes, with one MPI process on each node? (And perhaps OpenMP or another threading solution within each process and node?)

**Comment by satishskamath** [comment]
Hi @pkopta and @LourensVeen ,

Thank you for both your replies. I will tell you what I am currently working on, but the feature I ask is applicable to many other instances, such as when I want 2 MPI jobs running on different nodes and do not want them to run on the same node even by chance. 
@LourensVeen the scenario that you specify is possible to control within MPI itself I think either by using a rankfile or by specifying OpenMP threads via `--map-by ppr:Tasks_Per_Node:node:pe=ncores` . 

What I am trying to do is work on an embarrassingly parallel work flow with many python jobs (lets call these jobs A1, A2, ...) which run along with a master python process that hosts a shared memory (lets call this job B) on each node. Each of these A1, A2 ... write a part on the shared memory hosted by B, therefore B runs until A1, A2 ... on that particular node are not completed. Since this is shared memory, I need job B to run on 1 cpu on each node.

**Comment by LourensVeen** [comment]
Hi Satish,

Yes, I was thinking that you could do that with mpirun, that's why I asked :). QCG-PJ lets you specify additional mpirun options, so I thought that that could work. But it's not what you're doing, so maybe not the best solution.

When a QCG-PilotJob job is ready to run (i.e. you've submitted it and any dependencies have finished), then QCG-PJ will look at what resources it requires and what it has available, and try to find some free resources to run it on. If it finds a suitable set of free resources, the job is started, and those resources are marked as occupied. They will then be unavailable to other jobs until the present job finishes.

So, one thing that will definitely not work is to submit A and B as separate jobs to QCG-PJ, because they need to share resources. In that sense, your problem is similar to mine as explained in #65. This is a fundamental issue: QCG-PJ assumes that jobs form a Directed Acyclic Graph-based workflow, and that each job is basically a function that can be run independently of all other jobs. The only dependencies it supports are of the task-A-must-finish-before-task-B-can-start variety. We have tasks that communicate with each other while they are running, and this is something that QCG-PJ doesn't understand.

Would it be possible to create a script that starts one instance of B and as many instances of A as you have cores? Then you could ask QCG-PJ to run that script (or as many copies of it as you have nodes) using Piotr's settings above, and it should work. One of my users has done something similar in the past, launching a MUSCLE3 simulation on each node using QCG-PJ, and then using MUSCLE3 to coordinate as many instances of a submodel as there were cores available within the node. MUSCLE3 now has QCG-PJ integrated so this is no longer needed, but it did work.

**Comment by satishskamath** [comment]
@LourensVeen and @pkopta ,

Sorry for the late reply within the issue. :)
I got this to work using SLURM script outside of QCG pilot. I am initiating a shared memory instance using a python job outside. The shared memory instance survives even after the end of the first python call. Then executing the QCG-pilot job with jobs filling this shared memory and again unlinking the shared memory with the python job again after all jobs from QCG are done. The jobscript that invokes everything looks like this. 
```
#!/bin/bash
#SBATCH --job-name=qcgpilotjob-ex
#SBATCH --nodes=2
#SBATCH --time=00:10:00
#SBATCH --exclusive
#SBATCH --partition=thin

# NOTE: Change number of nodes at all places including the srun statements at the bottom if changed at the top.

module load 2020
module load Python/3.8.2-GCCcore-9.3.0
module load QCG-PilotJob/0.12.3-foss-2020a

# Change this path to where ever EnergyPlus is installed
export PATH=/home/$(whoami)/.local/easybuild/Centos8/2020/software/EnergyPlus/9.4.0-GCC-9.3.0:$PATH

# Running 1 task per node for initiating shared memory and finally unlinking it as well.
srun --ntasks-per-node=1 --nodes=2 python3 initiate_shared_memory.py
python3 qcg_pilot_energyplus.py
srun --ntasks-per-node=1 --nodes=2 python3 shared_memory_unlink.py

```
