### ISSUE TITLE
Document how to run tests

### ISSUE THREAD

**Issue by LourensVeen** [vecma-project/QCG-PilotJob#90]
There seems to be some kind of Docker-based testing infrastructure, but it's not obvious to me how to run the tests. It seems that I need to build some Docker containers, then start a container or two, possibly via the shell scripts in the root of the repo? Would it be possible to document this a bit, maybe in the README or in the documentation somewhere?

**Comment by LourensVeen** [comment]
Ah, `python -m pytest src/` (from .travis.yml) seems to run some tests. I'd still like to know whether that runs all the tests, or whether something needs to be done with the Docker stuff as well. Also, maybe useful to know since Travis is gone or almost gone, at NLeSC we've been moving stuff over to GitHub Actions, and it's working well for us as a replacement.

**Comment by pkopta** [comment]
As to the executing slurm tests i've created a pull request (https://github.com/vecma-project/QCG-PilotJob/pull/93) with documentation and some refinements related to the slurm tests. Currently, due to the long building time of docker containers the slurm tests are manually executed, not with the travis as general tests. As to the replacement of Travis, to be honest I didn't have time to look at alternatives. In future we might migrate to other platform, but currently it's not a priority for me.

**Comment by LourensVeen** [comment]
That looks good! Could you also add the command for running the non-Docker tests locally? I like to do that before making a commit, just to check that I didn't break anything. Otherwise I'd have to commit, push, then make a pull request just to see that there's a typo somewhere.

**Comment by pkopta** [comment]
I've updated document TESTS.md in https://github.com/vecma-project/QCG-PilotJob/pull/93, where I've described how to run locally just general tests.

**Comment by LourensVeen** [comment]
Perfect!

**Comment by LourensVeen** [comment]
Closing this, thanks again!
